services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
